{% set name = "windows-terminal" %}
{% set version = "1.22.11141.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/terminal/releases/download/v{{ version }}/Microsoft.WindowsTerminal_{{ version }}_x64.zip
    sha256: 8531822d3bf87625874dbffee632260d2390ca3b8cf67b0d2176957376c794cf
  - url: https://raw.githubusercontent.com/microsoft/terminal/v{{ version }}/LICENSE
    sha256: 5d177f23ecfeb0ea8e050b6a5a16355e1ae9a0b286436ca8f83ed08b3795be6b
  - url: https://raw.githubusercontent.com/microsoft/terminal/v{{ version }}/NOTICE.md
    sha256: f2a21ffa8034b40efd99188309053e16a9497342bf96515127e099959043b700

build:
  skip: true  # [not win]
  number: 0
  missing_dso_whitelist:
    - "*"
  script: |
    robocopy . "%PREFIX%\windows-terminal" /E /COPY:DAT
    if %ERRORLEVEL% geq 8 exit 1
    tree /F "%PREFIX%\windows-terminal"
    robocopy "%RECIPE_DIR%" "%PREFIX%\Scripts" wt.cmd
    if %ERRORLEVEL% geq 8 exit 1
requirements:
  run:
    - vc

test:
  commands:
    - where wt
    - if not exist %PREFIX%\\windows-terminal\\wt.exe exit 1

# The authors explicitly allowed the redistribution of the binary files
# https://github.com/microsoft/terminal/issues/15740#issuecomment-1648592594
about:
  home: https://github.com/microsoft/terminal
  summary: 'The new Windows Terminal and the original Windows console host, all in the same place!'
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - NOTICE.md

extra:
  recipe-maintainers:
    - "0xbe7a"
