{% set name = "windows-terminal" %}
{% set version = "1.21.3231.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/terminal/releases/download/v{{ version }}/Microsoft.WindowsTerminal_{{ version }}_x64.zip
    sha256: 8fb268b93c9b99d6cf553709c2c58bf1b2ff4b364199152e09221dfb2a44bbf5
  - url: https://raw.githubusercontent.com/microsoft/terminal/v{{ version }}/LICENSE
    sha256: 5d177f23ecfeb0ea8e050b6a5a16355e1ae9a0b286436ca8f83ed08b3795be6b
  - url: https://raw.githubusercontent.com/microsoft/terminal/v{{ version }}/NOTICE.md
    sha256: 26090ae00d6c21e319a273a4e9c3e5128bb62dabb5d5c74e59c17d5489938e81

build:
  skip: true  # [not win]
  number: 0
  missing_dso_whitelist:
    - "*"
  script: |
    robocopy . "%PREFIX%\windows-terminal" /E /COPY:DAT
    if %ERRORLEVEL% geq 8 exit 1
    tree /F "%PREFIX%\windows-terminal"
    robocopy "%RECIPE_DIR%" "%PREFIX%\Scripts" wt.cmd
    if %ERRORLEVEL% geq 8 exit 1
requirements:
  run:
    - vc

test:
  commands:
    - where wt
    - if not exist %PREFIX%\\windows-terminal\\wt.exe exit 1

# The authors explicitly allowed the redistribution of the binary files
# https://github.com/microsoft/terminal/issues/15740#issuecomment-1648592594
about:
  home: https://github.com/microsoft/terminal
  summary: 'The new Windows Terminal and the original Windows console host, all in the same place!'
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - NOTICE.md

extra:
  recipe-maintainers:
    - "0xbe7a"
